module.exports = {
  introText1: 'Welcome to the 511 Contra Costa "Text-Your-Commute" Challenge.',
  introText2: 'Earn rewards for walking, biking, ridesharing, or taking public transit to/from work. More info: http://511cc.org/tyc',
  questions: [
    'Question 1 of 7: What is your email address? (This is how we will contact you with rewards)',
    'Question 2 of 7: What is your home zipcode?',
    'Question 3 of 7: What is your work zipcode?',
    'Question 4 of 7: What is your age?',
    'Question 5 of 7: Do you work on weekends? (Y/N)',
    'Question 6 of 7: Do you own a car? (Y/N)',
    'Question 7 of 7: Do you typically drive alone to work? (Y/N)'
  ],
  under18Warning: 'Sorry, this program is only available to users 18 and older. Thank you for your interest.',
  introThankYouText: 'Thanks! We\'ll text you each day for your AM and PM commutes for the next 3 weeks.',
  daily: 'Did you commute today? (Y/N)',
  dailyThankYouText: 'Thanks for your answer. Keep logging your trips to be eligible for prizes. Reply STOP to stop receiving messages.',
  dailyMorning: 'How did you commute this morning? (Select up to 2 modes, separated by spaces) 1. Carpool 2. Transit 3. Ride Share App 4. Walk 5. Bike 6. Drive alone 7. Other',
  dailyEvening: 'How did you commute this evening? (Select up to 2 modes, separated by spaces) 1. Carpool 2. Transit 3. Ride Share App 4. Walk 5. Bike 6. Drive alone 7. Other',
  dailyNoCommuteText: 'OK, we\'ll ask you tomorrow about your commute.',
  modeOptions: [
    '1: Carpool',
    '2: Transit',
    '3: Ride Share App',
    '4: Walk',
    '5: Bike',
    '6: Drive alone',
    '7: Other'
  ],
  invalidYN: 'Please respond with a "Y" for yes or "N" for No.',
  carpoolCount: 'How many people were in your carpool?',
  carpoolRole: 'Were you the driver of the carpool? (Y/N)',
  ridershareOption: 'What type of rideshare did you use? 1. UberPool/Uber Express Pool 2. Lyft Shared 3. UberX 4. Lyft Regular 5. Other',
  ridershareCount: 'How many passengers (excluding the driver, but including yourself) were in your rideshare?',
  surveyClosed: 'The "Text-Your-Commute" Challenge is closed.',
  surveyThankyou: 'Thanks for completing the "Text-Your-Commute" Challenge. We\'ll contact you in a few weeks with more information about your participation.',
  emailSubject: 'Welcome to the Text-Your-Commute Challenge',
  emailBody: 'Congratulations, you’re signed up for the Text-Your-Commute Challenge! You’ll earn points for each commute trip you make without driving solo.\n\nHow it works: For three weeks, you\'ll get two texts a day (10am and 7pm) asking how you made your commute. You get a point for each ‘clean’ one-way trip you make – carpooling, vanpooling, taking public transportation, walking and bicycling all qualify. Rack up 15 clean trips and earn $25. Get to 30 trips and your bonus rises to $50.\n\nTo qualify for the Challenge, you must live or work in Contra Costa, be 18 years of age or older, have a cell phone with the ability to text, and would otherwise drive alone to or from work. For more information on prizes & eligibility, visit the Text-Your-Commute webpage www.511cc.org/tyc. If you have additional questions, please email tips@511contracosta.org.\n\nThe Text-Your-Commute Challenge is brought to you by 511 Contra Costa – a Transportation Demand Management program which promotes alternatives to driving alone. Funding is provided by the Bay Area Air Quality Management District’s Transportation Fund for Clean Air and the Contra Costa Transportation Authority.',
  emailHtml: '<p>Congratulations, you’re signed up for the Text-Your-Commute Challenge! You’ll earn points for each commute trip you make without driving solo.</p><p><b>How it works:</b> For three weeks, you\'ll get two texts a day (10am and 7pm) asking how you made your commute. You get a point for each ‘clean’ one-way trip you make – carpooling, vanpooling, taking public transportation, walking and bicycling all qualify. Rack up 15 clean trips and earn $25. Get to 30 trips and your bonus rises to $50.</p><p>To qualify for the Challenge, you must live or work in Contra Costa, be 18 years of age or older, have a cell phone with the ability to text, and would otherwise drive alone to or from work. For more information on prizes & eligibility, visit the Text-Your-Commute webpage www.511cc.org/tyc. If you have additional questions, please email tips@511contracosta.org.</p><p>The Text-Your-Commute Challenge is brought to you by 511 Contra Costa – a Transportation Demand Management program which promotes alternatives to driving alone. Funding is provided by the Bay Area Air Quality Management District’s Transportation Fund for Clean Air and the Contra Costa Transportation Authority.</p>',
  eightTrips: 'Congratulations! You’ve taken 8 green trips and reached the Bronze tier ($10)!',
  sixteenTrips: 'Congratulations! You’ve taken 16 green trips and reached the Silver tier ($25)!',
  thirtyTwoTrips: 'Congratulations! You’ve taken 32 green trips and reached the Gold Tier ($50)! You’re a Text Your Commute Challenge winner! (You will continue to receive texts for the rest of your three week challenge time to encourage you to keep commuting green!)'
};
